version: '3.7'
services:
    postgres:
        image: postgres:10-alpine
        environment:
            - POSTGRES_USER=airflow-mwaa
            - POSTGRES_PASSWORD=airflow-mwaa
            - POSTGRES_DB=airflow-mwaa
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - "${PWD}/db-data:/var/lib/postgresql/data"

    resetdb:
        image: amazon/mwaa-local:2_2
        platform: "linux/amd64"
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - "${PWD}/dags:/usr/local/airflow/dags"
            - "${PWD}/plugins:/usr/local/airflow/plugins"
            - "${PWD}/logs:/usr/local/airflow/logs"
            - "${PWD}/tmp:/tmp"
            - "${PWD}/docker/config/requirements:/usr/local/airflow/requirements"
        ports:
            - "8088:8080"
        command: resetdb
